
apiVersion: v1
kind: Service
metadata:
  name: frontendhorarios-service
spec:
  type: LoadBalancer
  selector:
    app: frontendhorarios
  ports:
    - name: http
      protocol: TCP
      nodePort: 32000
      port: 3000
      targetPort: 3000