apiVersion: v1
kind: Service
metadata:
  name: backendhorarios-service
spec:
  type: LoadBalancer
  selector:
    app: backendhorarios
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30001