apiVersion: v1
kind: Service
metadata:
  name: backendempleados-service
spec:
  type: LoadBalancer
  selector:
    app: backendempleados
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30000